name: VanillaPlus
version: 1.6.1
main: VanillaPlus.MainLoader
api-version: 1.21
authors: [Ghosty]
description: None to see here.
commands:
  togglestats:
    description: Toggle stats tracking
    usage: /togglestats [item]
  clearstats:
    description: Clear all stats from held item
    usage: /clearstats
  vp:
    description: Main command
    usage: /vp <command> [args]
    aliases: [vanillaplus]
